    # Video info
Video_type: avi
Video_path: D:/mouse/
scorer: tang
channels: 3
save_predicted_video: True
colors: 
- (255,50,50)
- (50,255,50)
- (75,0,130)
- (0,0,205)
- (173,216,230)
- (47,79,79)
- (240,255,240)
- (85,107,47)
- (253,245,230)
- (255,228,196)
- (255,160,122)
- (165,42,42)
- (105,105,105)
- (216,191,216)
- (127,255,0)
- (205,133,63)
- (178,34,34)
- (0,88,34)
- (178,0,69)
- (240,66,240)
- (85,107,147)
- (55,245,230)

    # Model info
model_path: singlemouse_model/_117481/cp.ckpt
pcutoff: 0.2
